### ISSUE TITLE
False positive when a new node is connected?

### ISSUE THREAD

**Issue by shun159** [rabbitmq/aten#21]
Hello, aten developer.
Thank you for your works, very helpful.

When registered a connected node, aten_detector sends a down message at first.  I expected that I could receive an up message after register a connected node.

Is this by design?
If so, please close this.

**Comment by michaelklishin** [comment]
Yes, this is by design. See #13 and https://github.com/rabbitmq/aten/commit/634f9a00b4b74de880d834fdce6d8d541bec858a, including some tests.

I can see the argument for emitting an `up` event for newly registered nodes, so we will consider #22 and I will file a separate issue with a more specific description. Thank you for contributing!
